### ISSUE TITLE
Migration questions 

### ISSUE THREAD

**Issue by mtangoo** [eranif/Notebook#1]
Hi Eran, 
I want to migrate my app to the notebook but I have questions 
1.  Is this the same as CL notebook? 
2.  Is API compatible with Aui notebook? 
Thanks

**Comment by eranif** [comment]
Yes, its the same as CodeLite
The API should be 99% similar to wxAuiNotebook

**Comment by mtangoo** [comment]
Cool, I will move to it. looks great. is there a tutorial on dealing with tabs and colors? or should I dig the code?
