### ISSUE TITLE
Migrating from AuiNotebook Questions

### ISSUE THREAD

**Issue by mtangoo** [eranif/Notebook#2]
Today I tried to Migrate from wxAuiNotebook and I failed. I Could not find equivalent for wxEVT_AUINOTEBOOK_TAB_RIGHT_UP. Is there any?

**Comment by eranif** [comment]
There is no equivalent event.
Instead I have implemented `Notebook::SetMenu(wxMenu* menu)` which is displayed when user right click on the active tab

**Comment by mtangoo** [comment]
Thanks. That's enough

**Comment by mtangoo** [comment]
I will leave it open incase I meet any further questions

**Comment by eranif** [comment]
Just open a new one, or post on CodeLite's forum

**Comment by mtangoo** [comment]
Okay thanks
