### ISSUE TITLE
Right Click  (Context) menu on non selected Item

### ISSUE THREAD

**Issue by mtangoo** [eranif/Notebook#3]
I find this troubling, especially in CodeLite, and since it s originating here, I thought I would open issue here. 
Sometimes I want to do something (like right click -> close) the tab that isn't active, but I find I have to select it before I get context menu.
Is it possible to have both world (or in case I missed, any options). I want to implement in my app using this control and also would love to see it back in CodeLite!

**Comment by eranif** [comment]
why don't you use the mouse scroll button to close inactive tab?

**Comment by mtangoo** [comment]
Because its a laptop. But then I may want to copy path (I have context menu for that) or just open the folder where that file is. All these have no interest on content of the notebook page

**Comment by eranif** [comment]
Fixed

**Comment by mtangoo** [comment]
I appreciate sir. Thanks

**Comment by mtangoo** [comment]
and how do I show the Context menu for this tab? I can catch event and know the tab. Only how to show the menu like in visible tabs!

**Comment by eranif** [comment]
that is up to you... just catch the event construct your menu and call `PopupMenu`

**Comment by mtangoo** [comment]
Great! I thought there is something a la SetMenu.

**Comment by mtangoo** [comment]
I have checked the sources and you send event when the current tab is not active. I understand that since Notebook handles menu. but still there are other useful information (like tab index) that are needed. So I think the best way is to send the event even for active tab.

To make life even simpler you can add ShowTabMenu() method or something that user will have to call to the event in order to show it, thereby leaving the choice to the user on when to show menu.

I can make PR for that, if it gets green light!
