### ISSUE TITLE
m_tabCtrl is private

### ISSUE THREAD

**Issue by mtangoo** [eranif/Notebook#6]
I wanted to access m_tabCtrl so that I can calculate current tab index and found its private and so unavailable in my current class. Is there specific reason or its just a bug?

**Comment by eranif** [comment]
the m_tabCtrl should not be accessesd. what's wrong with GetSelection ?

**Comment by mtangoo** [comment]
I wanted to get current **unselected** tab. Actually I have gone through a workaround to avoid this, its very hackish and I don't like it. The major issue arises fro the fact that right up tab event is not sent when the right clicked tab is active one.

I will close this one as I have written the real issue in the other issue #3
